project:
  type: website
  output-dir: docs

website:
  title: "Jack A. Goldman"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - publications.qmd

format:
  html:
    theme: superhero
    default-image-extension: jpeg
    css: styles.css
    toc: true

editor: visual

