---
title: "Publications"
---

[Google Scholar](https://scholar.google.ca/citations?user=35QdBZ4AAAAJ&hl=en)

[ORCID iD](https://orcid.org/0000-0002-4535-983X)

In Prep

**Goldman JA**, Fortin MJ, James PMA. Moisture availability at short timescales influences wildfire burn severity in the boreal forest

Published

7). **Goldman JA**, Crane A, Feyten, LEA, E Collins, Brown GE. (2022) Disturbance cue communication is shaped by emitter diet and receiver background risk in Trinidadian guppies. Current Zoology 68(4), 433-440

6). Messaoud Y, Reid A, Tchebakova NM, **Goldman JA**, Hofgaard A. (2022) The Historical Complexity of Tree Height Growth Dynamic Associated with Climate Change in Western North America. Forests 13(5), 738

5). Crane AL, Bairos-Novak KR, **Goldman JA**, Brown GE. (2021) Chemical disturbance cues in aquatic systems - a review and prospectus. Ecological Monographs 92(1), e10487 [Link](https://doi.org/10.1002/ecm.1487)

4). Brown GE, Demers EM, **Goldman JA**, Singh A, Ferrari MCO, Chivers DP. (2020) Unpredictable risk enhances induced neophobia in Northern red-bellied dace. Animal Behaviour 168, 121-127.

3). **Goldman JA**, Desormeaux IS, Brown GE. (2020) Disturbance cues function as sources of risk assessment information under natural conditions. Freshwater Biology. 65(5), 981-986.

2). **Goldman JA**, Feyten LEA, Ramnarine IW, Brown GE. (2020). Sender and receiver experience with risk alters the response to disturbance cues by Trinidadian guppies. Current Zoology 66(3), 255-261.

## 1). **Goldman JA**, Singh A, Demers EM, Feyten LEA, Brown GE. (2019) Does donor group size matter? The response of Trinidadian guppies and Convict cichlids to disturbance cues from conspecific and heterospecific donors. Canadian Journal of Zoology, 97(4) 319-325. \*Selected as Editor's Choice
